namespace KoiCatalog.Plugins.Koikatu
{
    public enum Personality
    {
        Sexy = 0x0,
        Ojousama = 0x1,
        Snobby = 0x2,
        Kouhai = 0x3,
        Mysterious = 0x4,
        Weirdo = 0x5,
        YamatoNadeshiko = 0x6,
        Tomboy = 0x7,
        Pure = 0x8,
        Simple = 0x9,
        Delusional = 0xA,
        Motherly = 0xB,
        BigSisterly = 0xC,
        Gyaru = 0xD,
        Delinquent = 0xE,
        Wild = 0xF,
        Wannabe = 0x10,
        Reluctant = 0x11,
        Jinxed = 0x12,
        Bookish = 0x13,
        Timid = 0x14,
        TypicalSchoolgirl = 0x15,
        Trendy = 0x16,
        Otaku = 0x17,
        Yandere = 0x18,
        Lazy = 0x19,
        Quiet = 0x1A,
        Stubborn = 0x1B,
        OldFashioned = 0x1C,
        Humble = 0x1D,
        Friendly = 0x1E,
        Willful = 0x1F,
        Honest = 0x20,
        Glamorous = 0x21,
        Returnee = 0x22,
        Slangy = 0x23,
        Sadistic = 0x24,
        Emotionless = 0x25,
    }
}
