namespace KoiCatalog.Plugins.Koikatu
{
    public enum Personality
    {
        Sexy = 0x0,
        Ojousama = 0x1,
        Haughty = 0x2,
        Kouhai = 0x3,
        Mysterious = 0x4,
        SpaceCase = 0x5,
        YamatoNadeshiko = 0x6,
        Boyish = 0x7,
        Pure = 0x8,
        Simple = 0x9,
        EvilEye = 0xA,
        Motherly = 0xB,
        BigSister = 0xC,
        Gyaru = 0xD,
        Delinquent = 0xE,
        Feral = 0xF,
        Wannabe = 0x10,
        Rebel = 0x11,
        Unlucky = 0x12,
        Bookish = 0x13,
        Bashful = 0x14,
        TypicalHeroine = 0x15,
        Trendy = 0x16,
        Otaku = 0x17,
        Yandere = 0x18,
        Lazy = 0x19,
        Quiet = 0x1A,
        Stubborn = 0x1B,
        OldFashioned = 0x1C,
        Docile = 0x1D,
        Friendly = 0x1E,
        Determined = 0x1F,
        Honest = 0x20,
        Charming = 0x21,
        Returnee = 0x22,
        Slangy = 0x23,
        Sadistic = 0x24,
        Emotionless = 0x25,
    }
}
